### ISSUE TITLE
ACPCore.h not found when importing <ACPCore/ACPCore.h> using cordova-acpcore 

### ISSUE THREAD

**Issue by sofienekooli** [adobe/cordova-acpcore#8]
### Expected Behaviour

ACPCore should be found.

### Actual Behaviour

ACPCore is not found.

### Reproduce Scenario (including but not limited to)

npm i @adobe/cordova-acpcore

ionic cordova plugin add @adobe/cordova-acpcore

ionic cordova build ios

press play in xcode

#### Platform and Version

Ionic:

   Ionic CLI                     : 5.4.16
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.12
   @angular-devkit/schematics    : 9.1.7
   @angular/cli                  : 9.1.7
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 8.0.0
   Cordova Platforms : ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, (and 24 other plugins)

Utility:

   cordova-res (update available: 0.15.3) : 0.15.2
   native-run                             : not installed

System:

   ios-sim : 8.0.2
   NodeJS  : v12.13.0 (/usr/local/bin/node)
   npm     : 6.12.0
   OS      : macOS Big Sur
   Xcode   : Xcode 12.5 Build version 12E262

**Comment by bhandaribhuminpfizer** [comment]
you may need to used `cordova plugin add @adobe/cordova-acpcore` after platform add

**Comment by rymorale** [comment]
Hi @sofienekooli,
Are you still seeing this issue? If so, can you try updating the pods in the `platforms/ios` directory after adding the cordova-acpcore plugin? The steps are:

1. install the cordova-acpcore plugin: `cordova plugin add https://github.com/adobe/cordova-acpcore.git`
2. navigate to the created platform iOS directory `platform/ios`
3. run `pod update`
4. build the cordova app from the base app directory: `cordova build`

Thanks,
Ryan

**Comment by deepDevAstro** [comment]
Hi Team, I am also facing the same issue. Using POD UPDATE or POD INSTALL, it downloads the files but error still exists. Headers files are not found. Please help check the sample app for this as well given at https://github.com/adobe/cordova-acpsample


I am attaching the logs from xcode below. 

Analyze /Users/yg51/Desktop/Deepak_ID/cordova-acpsample-main/TestApp/platforms/ios/HelloCordova/Plugins/cordova-aepassurance/AEPAssurance_Cordova.m normal x86_64 (in target 'HelloCordova' from project 'HelloCordova')
    cd /Users/yg51/Desktop/Deepak_ID/cordova-acpsample-main/TestApp/platforms/ios
    export LANG\=en_US.US-ASCII
    /Users/yg51/Software/Xcode\ 2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target x86_64-apple-ios10.0-simulator -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=c99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path\=/Users/yg51/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/yg51/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Wunreachable-code -Wno-implicit-atomic-properties -Wno-objc-interface-ivars -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DWK_WEB_VIEW_ONLY\=0 -DWK_WEB_VIEW_ONLY\=0 -DDEBUG\=1 -DCOCOAPODS\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Users/yg51/Software/Xcode\ 2.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -fobjc-abi-version\=2 -fobjc-legacy-dispatch -D__clang_analyzer__ -Xclang -analyzer-output\=plist-multi-file -Xclang -analyzer-config -Xclang path-diagnostics-alternate\=true -Xclang -analyzer-config -Xclang report-in-main-source-file\=true -Xclang -analyzer-config -Xclang nullability:NoDiagnoseCallsToSystemHeaders\=true -Xclang -analyzer-checker -Xclang security.insecureAPI.UncheckedReturn -Xclang -analyzer-checker -Xclang security.insecureAPI.getpw -Xclang -analyzer-checker -Xclang security.insecureAPI.gets -Xclang -analyzer-checker -Xclang security.insecureAPI.mkstemp -Xclang -analyzer-checker -Xclang security.insecureAPI.mktemp -Xclang -analyzer-disable-checker -Xclang security.insecureAPI.rand -Xclang -analyzer-disable-checker -Xclang security.insecureAPI.strcpy -Xclang -analyzer-checker -Xclang security.insecureAPI.vfork -iquote /Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Intermediates.noindex/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/HelloCordova-generated-files.hmap -I/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Intermediates.noindex/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/HelloCordova-own-target-headers.hmap -I/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Intermediates.noindex/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/HelloCordova-all-non-framework-target-headers.hmap -ivfsoverlay /Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Intermediates.noindex/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/all-product-headers.yaml -iquote /Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Intermediates.noindex/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/HelloCordova-project-headers.hmap -I/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/include -I/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/usr/local/lib/include -I/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Intermediates.noindex/UninstalledProducts/include -I/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Intermediates.noindex/UninstalledProducts/iphonesimulator/include -I/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator -I/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/ACPAnalytics/ACPAnalytics.framework/Headers -I/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/ACPCore/ACPCore.framework/Headers -I/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/ACPPlaces/ACPPlaces.framework/Headers -I/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/ACPPlacesMonitor/ACPPlacesMonitor.framework/Headers -I/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/ACPUserProfile/ACPUserProfile.framework/Headers -I/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/AEPAssurance/AEPAssurance.framework/Headers -I/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/AEPCore/AEPCore.framework/Headers -I/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/AEPRulesEngine/AEPRulesEngine.framework/Headers -I/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/AEPServices/AEPServices.framework/Headers -I/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/ACPAnalytics/Headers -I/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/ACPCore/Headers -I/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/ACPIdentity/Headers -I/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/ACPLifecycle/Headers -I/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/ACPPlaces/Headers -I/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/ACPSignal/Headers -I/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/ACPUserProfile/Headers -I/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Intermediates.noindex/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/DerivedSources-normal/x86_64 -I/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Intermediates.noindex/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/DerivedSources/x86_64 -I/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Intermediates.noindex/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/DerivedSources -F/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator -F/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/ACPAnalytics -F/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/ACPCore -F/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/ACPPlaces -F/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/ACPPlacesMonitor -F/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/ACPUserProfile -F/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/AEPAssurance -F/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/AEPCore -F/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/AEPRulesEngine -F/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/AEPServices -F/Users/yg51/Desktop/Deepak_ID/cordova-acpsample-main/TestApp/platforms/ios/Pods/ACPAnalytics -F/Users/yg51/Desktop/Deepak_ID/cordova-acpsample-main/TestApp/platforms/ios/Pods/ACPCore -F/Users/yg51/Desktop/Deepak_ID/cordova-acpsample-main/TestApp/platforms/ios/Pods/ACPPlaces -F/Users/yg51/Desktop/Deepak_ID/cordova-acpsample-main/TestApp/platforms/ios/Pods/ACPUserProfile -include /Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Intermediates.noindex/PrecompiledHeaders/SharedPrecompiledHeaders/5796682821264158652/HelloCordova-Prefix.pch -MMD -MT dependencies -MF /Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Intermediates.noindex/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/StaticAnalyzer/HelloCordova/HelloCordova/normal/x86_64/AEPAssurance_Cordova.d --analyze /Users/yg51/Desktop/Deepak_ID/cordova-acpsample-main/TestApp/platforms/ios/HelloCordova/Plugins/cordova-aepassurance/AEPAssurance_Cordova.m -o /Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Intermediates.noindex/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/StaticAnalyzer/HelloCordova/HelloCordova/normal/x86_64/AEPAssurance_Cordova.plist

/Users/yg51/Desktop/Deepak_ID/cordova-acpsample-main/TestApp/platforms/ios/HelloCordova/Plugins/cordova-aepassurance/AEPAssurance_Cordova.m:15:9: fatal error: 'AEPAssurance/AEPAssurance.h' file not found
#import <AEPAssurance/AEPAssurance.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/yg51/Desktop/Deepak_ID/cordova-acpsample-main/TestApp/platforms/ios/HelloCordova/Plugins/cordova-aepassurance/AEPAssurance_Cordova.m:15:9: note: did not find header 'AEPAssurance.h' in framework 'AEPAssurance' (loaded from '/Users/yg51/Library/Developer/Xcode/DerivedData/HelloCordova-beuyvziyspdmohdwlzlrikutgiah/Build/Products/Debug-iphonesimulator/AEPAssurance')
1 error generated.
Command Analyze failed with a nonzero exit code

**Comment by rymorale** [comment]
Hi @deepDevAstro, there was a versioning issue with the cordova aepassurance wrapper. Can you try updating the app dependencies again? The issue should be resolved after updating.

Thanks,
Ryan

**Comment by pieshop** [comment]
I am also experiencing this issue. @rymorale I have followed you instructions to update the pods in platform/ios

After updating the pods/manifest.lock looks like this:

PODS:
  - ACPAnalytics (2.5.1):
    - ACPAnalytics/xcframeworks (= 2.5.1)
    - ACPCore (>= 2.9.0)
  - ACPAnalytics/xcframeworks (2.5.1):
    - ACPCore (>= 2.9.0)
  - ACPCore (2.9.4):
    - ACPCore/main (= 2.9.4)
  - ACPCore/main (2.9.4)

DEPENDENCIES:
  - ACPAnalytics (>= 2.2.3)
  - ACPCore (>= 2.6.1)

However, the build still fails with:

`Lexical or Preprocessor Issue
/cordova-app/platforms/ios/xxx/Plugins/cordova-acpcore/ACPCore_Cordova.m:13:9: 'ACPCore/ACPCore.h' file not found`

Looking inside /cordova-app/platforms/ios/xxx/Plugins/cordova-acpcore/ I have .m but no .h files

ACPCore_Cordova.m
ACPIdentity_Cordova.m
ACPLifecycle_Cordova.m
ACPSignal_Cordova.m

**Comment by rymorale** [comment]
Hi @pieshop,

The header files should be present in the `Pods` directory after the Cordova wrappers are installed and the cocoapods have been updated. On my machine the header files are available at `/platforms/ios/Pods/ACPCore/ACPCore.xcframework/ios-arm64_armv7_armv7s/Headers`. Can you check if the header search paths within Xcode point at the Pods directory? It should look like
<img width="1129" alt="Screen Shot 2021-09-17 at 8 38 19 AM" src="https://user-images.githubusercontent.com/11319121/133815930-189b799f-8134-4bb8-b727-053ff7b18b4f.png">
:

**Comment by rymorale** [comment]
Closing this issue as there are no further updates.

**Comment by bhandaribhumin** [comment]
@rymorale Do you plan to publish cordova-acpicore native package to npm?
e.g. https://www.npmjs.com/package/cordova-acpcore which solves many problems like deleting Makefile from our project as we use CI to build Android iOS app.
